//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.lesnikowskiMailProvider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.lesnikowskiMailProvider.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke downloade meddelelse fra mail server.
        /// </summary>
        internal static string dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiCouldNotGetMailsException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiCouldNotGetMailsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der skete en fejl i Lesnikowski Mail Provider komponenten.
        /// </summary>
        internal static string dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der var fejl i den indkommende mailmeddelelse.
        /// </summary>
        internal static string dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiIncomingMailErroneousException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiIncomingMailErroneousException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail&apos;ens encoding &quot;[encoding]&quot; er ikke valid. Encoding skal være base64..
        /// </summary>
        internal static string dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiInvalidEncodingException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiInvalidEncodingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail&apos;ens mimetype &quot;[mimetype]/[mimesubtype]&quot; er ikke gyldig. Det skal være application/soap+xml..
        /// </summary>
        internal static string dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiInvalidMimeTypeException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiInvalidMimeTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke logge på mailserveren &quot;[serveraddress]&quot; med adressen &quot;[replyaddress]&quot; og brugernavn &quot;[username]&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiLogOnException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiLogOnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail-opsætningen var ikke komplet.
        /// </summary>
        internal static string dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiMissingSettingsException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiMissingSettingsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail&apos;en kunne ikke afsendes.
        /// </summary>
        internal static string dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiSendException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_lesnikowskiMailProvider_LesnikowskiSendException", resourceCulture);
            }
        }
    }
}
