//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.communication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.communication.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke instantiere et proxy objekt til kommunikation med servicen.
        /// </summary>
        internal static string dk_gov_oiosi_communication_client_ProxyGenerationException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_client_ProxyGenerationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fandt flere dokumenttype-konfigurationer for dette dokument. Dette skyldes sandssynligvis en fejl i konfigurationsfilen..
        /// </summary>
        internal static string dk_gov_oiosi_communication_configuration_AmbiguousDocumentTypeResultException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_configuration_AmbiguousDocumentTypeResultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fandt flere dokumenttyper med id &quot;[guid]&quot;. Dette skyldes sandssynligvis en fejl i konfigurationsfilen..
        /// </summary>
        internal static string dk_gov_oiosi_communication_configuration_AmbiguousDocumentTypeResultFromIdException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_configuration_AmbiguousDocumentTypeResultFromIdExcepti" +
                        "on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fandt flere dokumenttyper med rodnavne &quot;[rootname]&quot;, rodnamespace &quot;[rootnamespace]&quot; og identifikationsdiskriminatorerne &quot;[identifierdiscriminators]&quot;. Dette skyldes sandssynligvis en fejl i konfigurationsfilen..
        /// </summary>
        internal static string dk_gov_oiosi_communication_configuration_AmbiguousDocumentTypeResultFromParametersException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_configuration_AmbiguousDocumentTypeResultFromParameter" +
                        "sException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentet [DocumentName] findes allerede i samlingen af dokumenttype-konfigurationer. Dette skyldes sandssynligvis at en dokumenttype er konfigureret 2 gange i konfigurationen.
        /// </summary>
        internal static string dk_gov_oiosi_communication_configuration_DocumentAllreadyAddedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_configuration_DocumentAllreadyAddedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke mappe værdien &quot;[value]&quot; til en nøgletype. Nøgler-type-angivelse i afsendte dokumenter er mappet til nøgle-type-definitioner i konfigurationen for hver dokumenttype. Der kunne ikke findes et match..
        /// </summary>
        internal static string dk_gov_oiosi_communication_configuration_KeyTypeMappingFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_configuration_KeyTypeMappingFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finde dokumenttypen. Dette skyldes sandssynligvis, at dokumenttypen ikke er konfigureret..
        /// </summary>
        internal static string dk_gov_oiosi_communication_configuration_NoDocumentTypeFoundException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_configuration_NoDocumentTypeFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finde dokumenttypen med id &quot;[guid]&quot;. Dette skyldes sandssynligvis, at dokumenttypen ikke er konfigureret..
        /// </summary>
        internal static string dk_gov_oiosi_communication_configuration_NoDocumentTypeFoundFromIdException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_configuration_NoDocumentTypeFoundFromIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finde dokumenttypen med rodnavne &quot;[rootname]&quot;, rodnamespace &quot;[rootnamespace]&quot; og identifikationsdiskriminatorerne &quot;[identifierdiscriminators]&quot;. Dette skyldes sandssynligvis, at dokumenttypen ikke er konfigureret..
        /// </summary>
        internal static string dk_gov_oiosi_communication_configuration_NoDocumentTypeFoundFromParametersException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_configuration_NoDocumentTypeFoundFromParametersExcepti" +
                        "on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl under instantieringen af en kommunikationskanal..
        /// </summary>
        internal static string dk_gov_oiosi_communication_CreatingCommunicationChannelFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_CreatingCommunicationChannelFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finde den aktuelle servicehost..
        /// </summary>
        internal static string dk_gov_oiosi_communication_CurrentServiceHostSearchFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_CurrentServiceHostSearchFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En SOAP fault meddelelse blev returneret af det kaldte endpoint. Beskeden er: &apos;[fault]&apos;. Fejlen skyldes: &apos;[source]&apos;..
        /// </summary>
        internal static string dk_gov_oiosi_communication_FaultReturnedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_FaultReturnedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den angivet TCP port &quot;[tcpportnumber]&quot; er ikke indenfor det gyldige interval 0-65536..
        /// </summary>
        internal static string dk_gov_oiosi_communication_InvalidTcpPortException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_InvalidTcpPortException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den type endpoint applikationen har valgt at lytte på er ikke supporteret. &apos;[type]&apos; endpoints kan ikke bruge som serivce endpoints..
        /// </summary>
        internal static string dk_gov_oiosi_communication_listener_EndpointTypeNotSupportedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_listener_EndpointTypeNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No unique endpoint was given for the RASP Listener. Make sure your ListenerIdentity and App.Config only defines one, and only one, endpoint of type [type]..
        /// </summary>
        internal static string dk_gov_oiosi_communication_listener_ListenerDoesNotHaveExactlyOneEndpointException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_listener_ListenerDoesNotHaveExactlyOneEndpointExceptio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no unique service endpoint configured.
        /// </summary>
        internal static string dk_gov_oiosi_communication_listener_NoUniqueEndpointException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_listener_NoUniqueEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke starte lytningen på følgende adresse(r) &quot;[listeningaddresses]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_communication_listener_StartListeningFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_listener_StartListeningFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke stoppe lytningen på følgende adresse(r) &quot;[listeningaddresses]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_communication_listener_StopListeningFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_listener_StopListeningFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find listener to the service host &quot;[currentservicehostname]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_communication_ListenerSearchFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_ListenerSearchFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der var ikke sat tilstrækkelige credentials. Både et klient- og servercertifikat skal sættes, enten i konfigurationen eller programmatisk..
        /// </summary>
        internal static string dk_gov_oiosi_communication_MissingCredentialsException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_MissingCredentialsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementet &apos;[element]&apos; manglede i kommunikationsstakken. Dette skyldes enten at den ikke er korrekt konfigureret configured i app.config, eller sat programmatisk på bindingen..
        /// </summary>
        internal static string dk_gov_oiosi_communication_MissingStackElementException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_MissingStackElementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der skal angives et endpoint for at kunne generere et &apos;request&apos;..
        /// </summary>
        internal static string dk_gov_oiosi_communication_NoEndpointGivenException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_NoEndpointGivenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scheme &apos;[scheme]&apos; is not supported by RaspRequest..
        /// </summary>
        internal static string dk_gov_oiosi_communication_NotSupportedSchemeException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_NotSupportedSchemeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl i kommunikationsstakken..
        /// </summary>
        internal static string dk_gov_oiosi_communication_OiosiCommunicationException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_OiosiCommunicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient- og serverkonfiguration matcher ikke. Du bør sikre dig at den kaldte service overholder RASP profilen..
        /// </summary>
        internal static string dk_gov_oiosi_communication_ProtocolMismatchException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_ProtocolMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedlukning af kommunikationen fejlede..
        /// </summary>
        internal static string dk_gov_oiosi_communication_RequestShutdownException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_RequestShutdownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsendelse og modtagelse af et svar fejlede..
        /// </summary>
        internal static string dk_gov_oiosi_communication_SendingException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_SendingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOAP action &apos;[expected]&apos; var forventet på svaret men action &apos;[gotten]&apos; blev modtaget.
        /// </summary>
        internal static string dk_gov_oiosi_communication_UnexpectedReplyActionException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_UnexpectedReplyActionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der findes ingen der lytter til inkomne beskeder..
        /// </summary>
        internal static string dk_gov_oiosi_communication_WcfListenerSearchFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_WcfListenerSearchFailedException", resourceCulture);
            }
        }
    }
}
