//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.configuration.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationen kunne ikke læses fra stien [path].
        /// </summary>
        internal static string dk_gov_oiosi_configuration_ConfigurationCouldNotBeReadFromFileException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_configuration_ConfigurationCouldNotBeReadFromFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationen kunne ikke gemmes til stien [path]..
        /// </summary>
        internal static string dk_gov_oiosi_configuration_ConfigurationCouldNotBeWrittenException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_configuration_ConfigurationCouldNotBeWrittenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der skete en fejl under håndteringen af konfigurationen.
        /// </summary>
        internal static string dk_gov_oiosi_configuration_ConfigurationException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_configuration_ConfigurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der findes allerede en konfigurationssektion af denne type. Der kan kun eksistere en konfigurationssektion af hver type.
        /// </summary>
        internal static string dk_gov_oiosi_configuration_ConfigurationSectionAlreadyExistsException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_configuration_ConfigurationSectionAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationssektion klassen mangler enten en XmlRoot attribut, eller der er ikke associeret et namespace med den..
        /// </summary>
        internal static string dk_gov_oiosi_configuration_ConfigurationSectionMissingXmlRootAttributeException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_configuration_ConfigurationSectionMissingXmlRootAttributeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RASP konfigurationshandleren håndterer kun konfigurations-sektions-typer som har en default constructor defineret.
        /// </summary>
        internal static string dk_gov_oiosi_configuration_ConfigurationTypeHasNoDefaultConstructorException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_configuration_ConfigurationTypeHasNoDefaultConstructorException", resourceCulture);
            }
        }
    }
}
