//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.common.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke loade en instans af typen &apos;[type]&apos;..
        /// </summary>
        internal static string dk_gov_oiosi_common_CouldNotLoadTypeException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_CouldNotLoadTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke oprette en instans af typen &quot;[implementationnamespaceclass]&quot; i dll&apos;en &quot;[implementationassembly]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_common_CreateInstanceFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_CreateInstanceFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukendt servicenøgle type kode &quot;[endpointkeytypecode]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_common_UnknownEndpointTypeException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_UnknownEndpointTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finde KeyType [KeyType] i KeyTypeMappings listen..
        /// </summary>
        internal static string dk_gov_oiosi_common_UnknownKeyTypeValueException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_UnknownKeyTypeValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generel fejl i en hjælpeklasse..
        /// </summary>
        internal static string dk_gov_oiosi_common_UtilityException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_UtilityException", resourceCulture);
            }
        }
    }
}
