//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.security.ldap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.security.ldap.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke oprette en forbindelse til LDAP serveren på adressen &quot;[address]&quot; og port &quot;[port]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_ldap_ConnectingToLdapServerFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ldap_ConnectingToLdapServerFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke konvertere certifikat data fra LDAP serveren til et valididt x509 certifikat..
        /// </summary>
        internal static string dk_gov_oiosi_security_ldap_ConvertingSearchResultToCertificateFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ldap_ConvertingSearchResultToCertificateFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke loade lookup implementeringen af lookup-typen &quot;[lookuptype]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_ldap_FailedToLoadLookupTypeException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ldap_FailedToLoadLookupTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejlede instantieringen af et LDAP baseret ICertificateLookup objekt..
        /// </summary>
        internal static string dk_gov_oiosi_security_ldap_LdapCertificateLookupInitializationFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ldap_LdapCertificateLookupInitializationFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finde certifikatet på LDAP-serveren. Brugte føgende søgestreng &quot;[subjectstring]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_ldap_LdapCertificateNotFoundException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ldap_LdapCertificateNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er sket en general LDAP fejl..
        /// </summary>
        internal static string dk_gov_oiosi_security_ldap_LdapException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ldap_LdapException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der blev fundet flere certifikater på LDAP-serveren som matchede søgestrengen &quot;[subjectstring]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_ldap_LdapMultipleCertificatesFoundException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ldap_LdapMultipleCertificatesFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er ikke angivet noget assembly i Ldap config, som implementerer LDAP lookup klienten.
        /// </summary>
        internal static string dk_gov_oiosi_security_ldap_LdapNoImplementingAssemblyException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ldap_LdapNoImplementingAssemblyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er ikke angivet nogen klasse i Ldap config, som implementerer LDAP lookup klienten.
        /// </summary>
        internal static string dk_gov_oiosi_security_ldap_LdapNoImplementingClassException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ldap_LdapNoImplementingClassException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejlede at finde et eller flere matches med det regulære udtryk &quot;[patterns]&quot; i certifikat subject string &quot;[subject]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_ldap_PatternsDoesNotMatchException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ldap_PatternsDoesNotMatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke gemme certifikatet..
        /// </summary>
        internal static string dk_gov_oiosi_security_ldap_StoringCertificateFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ldap_StoringCertificateFailedException", resourceCulture);
            }
        }
    }
}
