//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.security.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mere end et certifikat der matchede de angivne kriterier blev fundet..
        /// </summary>
        internal static string dk_gov_oiosi_security_AmbigousLoadResult {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_AmbigousLoadResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er sket en generel certifikat håndterings fejl..
        /// </summary>
        internal static string dk_gov_oiosi_security_CertificateHandlingException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_CertificateHandlingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finde certifikatet i certifikatlageret. Søgte i lagerplaceringen &quot;[x509storelocation]&quot; med navnet &quot;[x509storename]&quot;. Søgte med &quot;[x509findtype]&quot; og søgestrengen &quot;[searchstring]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_lookup_CertificateLoaderCertificateNotFoundException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_lookup_CertificateLoaderCertificateNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fandt flere certifikater i certifikatlageret. Søgte i lagerplaceringen &quot;[x509storelocation]&quot; med navnet &quot;[x509storename]&quot;. Søgte med &quot;[x509findtype]&quot; og søgestrengen &quot;[searchstring]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_lookup_CertificateLoaderMultipleCertificatesFoundException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_lookup_CertificateLoaderMultipleCertificatesFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er sket en generel fejl i forsøget på at lave et opslag efter et certifikat..
        /// </summary>
        internal static string dk_gov_oiosi_security_lookup_CertificateLookupException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_lookup_CertificateLookupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finde det tilhørende certifikat.
        /// </summary>
        internal static string dk_gov_oiosi_security_lookup_CertificateNotFoundException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_lookup_CertificateNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der blev fundet flere certifkater ud fra de angivne kriterier.
        /// </summary>
        internal static string dk_gov_oiosi_security_lookup_MultipleCertificatesFoundException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_lookup_MultipleCertificatesFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søgningen efter et certifikat fejlede.
        /// </summary>
        internal static string dk_gov_oiosi_security_lookup_SearchFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_lookup_SearchFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifikatet er udløbet den &quot;[expiredate]&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_security_lookup_Validation_CertificateExpiredException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_lookup_Validation_CertificateExpiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifikatet fejlede kædevalideringen med status &quot;[chainstatus]&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_security_lookup_Validation_CertificateFailedChainValidationException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_lookup_Validation_CertificateFailedChainValidationException" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifikatet er ikke aktivt endnu, aktiveres den &quot;[activedate]&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_security_lookup_Validation_CertificateNotActivedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_lookup_Validation_CertificateNotActivedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifikatet er ikke i korrekt format.
        /// </summary>
        internal static string dk_gov_oiosi_security_lookup_Validation_CertificateNotInCorrectFormatException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_lookup_Validation_CertificateNotInCorrectFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det givet certifikat har flere cvr numre i subject. Certifikatet har følgende navn (&apos;friendlyName&apos;) &quot;[certificatefriendlyname]&quot; og subject &quot;[certificatesubject]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_oces_AmbigousSubjectCvrNumberException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_oces_AmbigousSubjectCvrNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke få OCES certifikattypen ud fra certifikatet med navnet &quot;[certificatefriendlyname]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_oces_FailedGetOcesCertificateTypeException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_oces_FailedGetOcesCertificateTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det givne certifikat er ikke et gyldigt OCES certifikat. Certifikatet har følgende navn (&apos;friendly name&apos;) &quot;[certificatefriendlyname]&quot; og subject &quot;[certificatesubject]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_oces_InvalidOcesCertificateException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_oces_InvalidOcesCertificateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det given streng &quot;[oidstring]&quot; er ikke gyldig. Det skal være i formattet &quot;x.x.x.x.x.x.x.x.x&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_oces_InvalidOcesCertificatePolicyOidException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_oces_InvalidOcesCertificatePolicyOidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det givne certifikat er ikke et gyldigt MOCES certifikat. Certifikatet har følgende navn (&apos;friendly name&apos;) &quot;[certificatefriendlyname]&quot; og subject &quot;[certificatesubject]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_oces_InvalidOcesEmployeeCertificateException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_oces_InvalidOcesEmployeeCertificateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det givne certifikat har ikke et cvr nummer i subject. Certifikatet har følgende navn (&apos;friendly name&apos;) &quot;[certificatefriendlyname]&quot; og subject &quot;[certificatesubject]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_oces_NoSubjectCvrNumberException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_oces_NoSubjectCvrNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signaturbeviset kan ikke færdiggøres da det allerede er processeret..
        /// </summary>
        internal static string dk_gov_oiosi_security_SignatureValidationProofAllreadyCompletedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_SignatureValidationProofAllreadyCompletedException", resourceCulture);
            }
        }
    }
}
