//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.uddi.ars {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.uddi.ars.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En uventet fejl opstod under håndtering af et binding sæt.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_ArsBindingSetUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_ArsBindingSetUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En uventet fejl opstod under håndtering af en binding.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_ArsBindingUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_ArsBindingUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En uventet fejl opstod under håndtering af en ARS business entity.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_ArsBusinessEntityUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_ArsBusinessEntityUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En uventet fejl opstod under håndtering af en ARS proces definition.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_ArsBusinessProcessDefinitionUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_ArsBusinessProcessDefinitionUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En uventet fejl opstod under håndtering af et endpoint sæt object.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_ArsEndpointSetUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_ArsEndpointSetUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En uventet fejl opstod under håndtering af en ARS endpoint.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_ArsEndpointUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_ArsEndpointUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er sket en generel ARS fejl..
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_ArsException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_ArsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En uventet fejl opstod i ArsLookup.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_ArsLookupUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_ArsLookupUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En uventet fejl opstod under håndtering af et process instance sæt object.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_ArsProcessInstanceSetUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_ArsProcessInstanceSetUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En uventet fejl opstod under håndtering af et process instance object.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_ArsProcessInstanceUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_ArsProcessInstanceUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er sket en uventet fejl under oprettelsen af et Ars endepunkt. Endepunktet har følgende id=&quot;[endpointid]&quot; navn=&quot;[endpointname]&quot; beskrivelse=&quot;[endpointdescription]&quot; og tilhører business med følgende id=&quot;[endpointbusinessid]&quot; .
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_CreateArsEndpointFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_CreateArsEndpointFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En uventet fejl opstod under sletning af en ARS entitet.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_DeleteEntityException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_DeleteEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangler Binding for Endpoint.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_MissingEndpointBindingFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_MissingEndpointBindingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangler Endpoint for Service Definition.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_MissingServiceDefinitionBindingFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_MissingServiceDefinitionBindingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er sket en uventet fejl under gemning af et Ars endepunkt. Endepunktet har følgende id=&quot;[endpointid]&quot; navn=&quot;[endpointname]&quot; beskrivelse=&quot;[endpointdescription]&quot; og tilhører business med følgende id=&quot;[endpointbusinessid]&quot; .
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_SaveArsEndpointFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_SaveArsEndpointFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er sket en uventet fejl under updateringen af et Ars endepunkt. Endepunktet har følgende id=&quot;[endpointid]&quot; navn=&quot;[endpointname]&quot; beskrivelse=&quot;[endpointdescription]&quot; og tilhører business med følgende id=&quot;[endpointbusinessid]&quot; .
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_UpdateArsEndpointFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_UpdateArsEndpointFailedException", resourceCulture);
            }
        }
    }
}
