//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.extension.wcf.Interceptor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.extension.wcf.Interceptor.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finde BindingElement &quot;[type]&quot; i WCF stakken..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_BindingElementNotInStackException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_BindingElementNotInStackException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingElement rækkefølge fejl. Elementet &quot;[before]&quot; skal være før &quot;[current]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_BindingElementOrderMismatchException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_BindingElementOrderMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der skete en fejl i interceptoren..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Channels_InterceptorChannelException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Channels_InterceptorChannelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [message].
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Channels_InterceptorChannelWrapperException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Channels_InterceptorChannelWrapperExceptio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der skete en intern fejl i serveren..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Channels_InterceptorInternalFailureException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Channels_InterceptorInternalFailureExcepti" +
                        "on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanaltypen &quot;[type]&quot; i protokolstakken er ikke understøttet..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Channels_UnsupportedChannelTypeException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Channels_UnsupportedChannelTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er sket en generel interceptor fejl i protokolstakken..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_InterceptorException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_InterceptorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der skete en intern fejl ved autorisationen..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Security_authorisation_AuthorisationProcessFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Security_authorisation_AuthorisationProces" +
                        "sFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er ikke adgang til serveren med klientcertifikat med navn &quot;[certificatefriendlyname]&quot; og subject &quot;[certificatesubject]&quot; samt dokumenttypen &quot;[documenttypefriendlyname]&quot;. .
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Security_authorisation_NotAuthorisedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Security_authorisation_NotAuthorisedExcept" +
                        "ion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsender certifikatet er trukket tilbage..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Security_CertificateRevokedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Security_CertificateRevokedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifikatet valideringen fejlede med fejlen: [error].
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Security_CertificateRevokedValidationFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Security_CertificateRevokedValidationFaile" +
                        "dException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunner ikke hente certifikatsubject ud af beskeden i protokolstakken (WCF) med følgende SOAP action &quot;[messageaction]&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Security_FailedToGetCertificateSubjectException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Security_FailedToGetCertificateSubjectExce" +
                        "ption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søgningen efter tag&apos;et &quot;[tagname]&quot; i security headeren gav intet resultat..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Security_Header_NoElementsFoundException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Security_Header_NoElementsFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søgningen efter tag&apos;et &quot;[tagname]&quot; i security headeren returnerede &apos;[results]&apos; resultater, hvilket er for mange..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Security_Header_ToManyElementsFoundException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Security_Header_ToManyElementsFoundExcepti" +
                        "on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke loade XML schema filen &quot;[filename]&quot;. Schema filen anvendes til at validere afsendte og modtagne beskeder af en bestemt type.
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Validation_Schema_FailedToLoadSchemaException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Validation_Schema_FailedToLoadSchemaExcept" +
                        "ion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke validere (XML Schema validere) dokumentet..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Validation_Schema_SchemaValidateDocumentFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Validation_Schema_SchemaValidateDocumentFa" +
                        "iledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOAP-meddelelsens body var tom ved schema validerings interceptoren, dvs der fandtes ingen meddelelse som kunne valideres.
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Validation_Schema_SchemaValidationInterceptionEmptyBodyException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Validation_Schema_SchemaValidationIntercep" +
                        "tionEmptyBodyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schematron valideringen forløb ikke succesfuldt..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Validation_Schematron_SchematronValidateDocumentFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Validation_Schematron_SchematronValidateDo" +
                        "cumentFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netværksmeddelelsens body var tom ved schematron validator interceptoren, dvs der fandtes ingen meddelelse som kunne valideres..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_Validation_Schematron_SchematronValidationInterceptionEmptyBodyException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_Validation_Schematron_SchematronValidation" +
                        "InterceptionEmptyBodyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke XSLT-transformere meddelelsen (med henblik på grafisk visning). Dette kan betyde, at der er fejl i meddelelsens struktur ift XSLT stylesheetet, eller at dette er forkert konfigureret..
        /// </summary>
        internal static string dk_gov_oiosi_extension_wcf_Interceptor_XsltTransform_XsltTransformFailedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_extension_wcf_Interceptor_XsltTransform_XsltTransformFailedException" +
                        "", resourceCulture);
            }
        }
    }
}
