//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.security.validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.security.validation.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsender certifikatet er udløbet den &quot;[expiredate]&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_security_validation_CertificateExpiredException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_validation_CertificateExpiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsender Certifikatet fejlede kædevalideringen med status &quot;[chainstatus]&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_security_validation_CertificateFailedChainValidationException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_validation_CertificateFailedChainValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsender certifikatet er ikke aktivt endnu, aktiveres den &quot;[activedate]&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_security_validation_CertificateNotActiveException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_validation_CertificateNotActiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifikatet er ikke i et korrekt format.
        /// </summary>
        internal static string dk_gov_oiosi_security_validation_CertificateNotInCorrectFormatException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_validation_CertificateNotInCorrectFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rod certifikatet &quot;[root]&quot; er ikke trusted.
        /// </summary>
        internal static string dk_gov_oiosi_security_validation_CertificateRootNotTrustedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_validation_CertificateRootNotTrustedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifikatet er ikke validt..
        /// </summary>
        internal static string dk_gov_oiosi_security_validation_CertificateValidationException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_validation_CertificateValidationException", resourceCulture);
            }
        }
    }
}
