//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.uddi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.uddi.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typen af service-nøglen &quot;[endpointkeytype]&quot; er ukendt..
        /// </summary>
        internal static string dk_gov_oiosi_uddi_category_UnknownEndpointTypeException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_category_UnknownEndpointTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finde kategorien med følgende TModel-nøgle &quot;[categorytmodelkey]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_uddi_CategoryMissingException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_CategoryMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid-strengen må ikke være den tomme Guid-streng.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_EmptyGuidException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_EmptyGuidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finde identiteten med følgende TModel-nøgle &quot;[identifiertmodelkey]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_uddi_IdentifierMissingException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_IdentifierMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den angivne GUID er tom..
        /// </summary>
        internal static string dk_gov_oiosi_uddi_UddiEmptyGuidException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_UddiEmptyGuidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er sket en fejl i forbindelse med håndteringen af serviceregisteret (UDDI)..
        /// </summary>
        internal static string dk_gov_oiosi_uddi_UddiException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_UddiException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaget i serviceregisteret (UDDI) for endpointet med ID &quot;[endpointKey]&quot; fejlede..
        /// </summary>
        internal static string dk_gov_oiosi_uddi_UddiLookupException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_UddiLookupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der blev returneret mere end ét endpoint fra serviceregisteret (UDDI). Dette kan skyldes at der både er registreret endpoints for fx email og http (hvilket er lovligt), men at opslagsbiblioteket er konfigureret til ikke at acceptere dette.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_UddiMoreThanOneEndpointException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_UddiMoreThanOneEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke angivet nogen implementerende assembly for opslag i serviceregisteret (UDDI) i konfigurationen.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_UddiNoImplementingAssemblyException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_UddiNoImplementingAssemblyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke angivet nogen implementerende klasse for opslag i serviceregisteret (UDDI) i factory konfigurationen..
        /// </summary>
        internal static string dk_gov_oiosi_uddi_UddiNoImplementingClassException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_UddiNoImplementingClassException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To identiske endpoints blev returneret fra serviceregisteret (UDDI). Dette skyldes en ulovlig registrering i registeret..
        /// </summary>
        internal static string dk_gov_oiosi_uddi_UddiTwoEqualEndpointsException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_UddiTwoEqualEndpointsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den angivne Guid-streng &quot;[Guid]&quot; har et forkert format..
        /// </summary>
        internal static string dk_gov_oiosi_uddi_UddiWrongGuidFormatException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_UddiWrongGuidFormatException", resourceCulture);
            }
        }
    }
}
