//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.security.revocation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.security.revocation.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifikatet &apos;[serialnumber]&apos; er spærret og er defor ikke pålideligt.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_CertificateRevokedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_CertificateRevokedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifikat checket mod OCSP timede ud efter &quot;[ocsptimeout]&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_CertificateRevokedTimeoutException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_CertificateRevokedTimeoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uventet fejl opstod i check af om certifikatet er gyldigt.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_CheckCertificateActivatedUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_CheckCertificateActivatedUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uventet fejl opstod i kæde-validering af certifikat.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_CheckCertificateChainUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_CheckCertificateChainUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en uventet fejl under selve kaldet til OCSP serveren.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_CheckCertificateOcspUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_CheckCertificateOcspUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en uventet fejl under kædevalidering af certifikatet.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_CheckCertificateRevokedUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_CheckCertificateRevokedUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en uventet fejl under check af certifikat typen..
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_CheckCertificateTypeUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_CheckCertificateTypeUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en uventet fejl under valideringen af certifikatet..
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_CheckCertificateValidUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_CheckCertificateValidUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en uventet fejl under check af om rod-certifikatet er aktiveret.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_CheckRootCertificateActivatedUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_CheckRootCertificateActivatedUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en uventet fejl under check af om rod-certifikatet er gyldigt.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_CheckRootCertificateValidUnexpectedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_CheckRootCertificateValidUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke loade lookup typen &quot;[lookuptype]&quot;. Dette skyldes sandssynligvis en fejlkonfiguration.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_FailedToLoadLookupTypeException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_FailedToLoadLookupTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout værdien &quot;[timeoutvalue]&quot; er ikke gyldig. Den skal være imellem &quot;[minvalue]&quot; og &quot;[maxvalue]&quot;..
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_InvalidOcspTimeoutValueException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_InvalidOcspTimeoutValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er sket en general OCSP fejl.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_OcspException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_OcspException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke angivet nogen implementerende assembly i OCSP konfigurationen.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_OcspNoImplementingAssemblyException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_OcspNoImplementingAssemblyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke angivet nogen implementerende klasse i OCSP konfigurationen.
        /// </summary>
        internal static string dk_gov_oiosi_security_ocsp_OcspNoImplementingClassException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_security_ocsp_OcspNoImplementingClassException", resourceCulture);
            }
        }
    }
}
