//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.common.validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.common.validation.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl i en underliggende attribut.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_ChildFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_ChildFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det obligatoriske felt &quot;[Felt]&quot; er ikke udfyldt.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_EmptyFieldFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_EmptyFieldFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori-værdien &quot;[Vaerdi]&quot; er ugyldig.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_InvalidCategoryValueFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_InvalidCategoryValueFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifikatet &quot;[CertificateSubject]&quot; har et ugyldigt format i subject.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_InvalidCertificateValueFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_InvalidCertificateValueFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cvr nummeret &quot;[Cvr]&quot; er ugyldigt. Skal bestå af 8 cifre, f.eks. &quot;23447123&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_InvalidCvrFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_InvalidCvrFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN nummeret &quot;[Ean]&quot; er ugyldigt. Skal bestå af 13 cifre, begyndende med &quot;57&quot;, f.eks. &quot;5737392019283&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_InvalidEanFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_InvalidEanFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nøglen &quot;[Noegle]&quot; er ugyldig.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_InvalidIdentifierValueFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_InvalidIdentifierValueFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nøgleværdien &quot;[Key]&quot; har et forkert format.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_InvalidKeyFormatFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_InvalidKeyFormatFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprogfeltets værdi &quot;[Sprog]&quot; er ugyldigt. Gyldige værdier er &quot;dk&quot;, &quot;en&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_InvalidLanguageValueFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_InvalidLanguageValueFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovt nummeret &quot;[Ovt]&quot; har et ugyldigt format.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_InvalidOvtFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_InvalidOvtFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri adressen &quot;[Uri]&quot; er ugyldigt. Fejlbesked: &quot;[Message]&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_InvalidUriFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_InvalidUriFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions nummeret &quot;[Version]&quot; er ugyldigt. Skal bestå af 3 cifre adskilt af &quot;.&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_InvalidVersionFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_InvalidVersionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det obligatorisk felt &quot;[Felt]&quot; mangler.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_RequiredFieldFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_RequiredFieldFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltet &quot;[Felt]&quot; må maksimalt have [MaxTegn] tegn.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_TooLongFieldFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_TooLongFieldFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uventet fejl under validering af &quot;[Vaerdi]&quot;, Fejlbesked: &quot;[Message]&quot;.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_UnexpectedFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_UnexpectedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprogangivelsen &quot;[language]&quot; er ugyldig.
        /// </summary>
        internal static string dk_gov_oiosi_common_validation_ValidationIsoLanguageException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_common_validation_ValidationIsoLanguageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der skal være mindst én binding (http eller email) associeret med et endpoint.
        /// </summary>
        internal static string dk_gov_oiosi_uddi_ars_MissingEndpointBindingFailure {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_uddi_ars_MissingEndpointBindingFailure", resourceCulture);
            }
        }
    }
}
