//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.gov.oiosi.communication.handlers.email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dk.gov.oiosi.communication.handlers.email.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indboksen kunne ikke kontaktes med de indtastede oplysninger. E-mail adresse: [mailaddress]. Bruger: [user]..
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_FailedToGetInboxException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_FailedToGetInboxException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den angivne IMAP mappe er ikke gyldig.
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_ImapBadFolderPathException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_ImapBadFolderPathException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indboksen skiftede til en ulovlig tilstand (fra &quot;[FromState]&quot; til &quot;[ToState]&quot;).
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_InboxIllegalStateTransactionException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_InboxIllegalStateTransactionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indboksen var ikke i en gyldig tilstand &quot;[State]&quot; da operationen blev udført. Det sker typisk hvis indboksen er lukket ned og der forsøges at sende post..
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_InboxInvalidStateException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_InboxInvalidStateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En tilstand &quot;[State]&quot; i indboksen er ikke håndteret. Dette kan ske hvis der er introduceret nye tilstande i InboxState..
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_InboxUnhandledStateException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_InboxUnhandledStateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meddelelsesobjektet indeholder ikke den nødvendige information til at skabe en email som overholder &quot;Smtp/MIME Base64 Transport Binding for SOAP 1.2&quot; protokollen. Adressen &apos;[uri]&apos; har ikke den korrekte syntaks. Formater adressen som &apos;mailto:a@b.com/servicepath&apos; eller &apos;mailto:a@b.com?x-service-path=&apos;servicepath&apos;&apos;.
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_MailBindingAddressNotCompliantException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_MailBindingAddressNotCompliantException" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meddelelsesobjektet indeholder ikke den nødvendige information til at skabe en email som overholder &quot;Smtp/MIME Base64 Transport Binding for SOAP 1.2&quot; protokollen. Headeren &apos;[missingField]&apos; mangler.
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_MailBindingFieldMissingException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_MailBindingFieldMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailboksen er allerede lukket.
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_MailboxClosedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_MailboxClosedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er sket en email-relateret fejl.
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_MailHandlerException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_MailHandlerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailserveren er ikke konfigureret.
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_MailServerConfigurationMissingException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_MailServerConfigurationMissingException" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling-mønsteret &apos;[pattern]&apos; er ikke understøttet af implementationen &apos;[implementation]&apos;.
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_MailServerPollingPatternNotSupportedException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_MailServerPollingPatternNotSupportedExc" +
                        "eption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meddelelsesobjektet indeholder ikke den nødvendige information til at skabe en email som overholder &quot;Smtp/MIME Base64 Transport Binding for SOAP 1.2&quot; protokollen..
        /// </summary>
        internal static string dk_gov_oiosi_communication_handlers_email_MessageNotCompliantWithMailBindingException {
            get {
                return ResourceManager.GetString("dk_gov_oiosi_communication_handlers_email_MessageNotCompliantWithMailBindingExcep" +
                        "tion", resourceCulture);
            }
        }
    }
}
